# dynamic config
ARG             BUILD_DATE
ARG             VCS_REF
ARG             VERSION

# build
FROM            golang:1.18-alpine as builder
RUN             apk add --no-cache git gcc musl-dev make
ENV             GO111MODULE=on
RUN		        git clone https://github.com/drinaaf/berty.git
WORKDIR         berty
RUN             go mod download
WORKDIR         go
RUN             make go.install
CMD 		["berty", "daemon"]

